# Generated by Django 2.2.4 on 2019-08-18 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('color', models.CharField(default='#ffffff', max_length=30)),
                ('column', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('item_type', models.CharField(default='note', editable=False, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(default='#ffffff', max_length=30)),
                ('column', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sno', models.IntegerField(default=0)),
                ('item_type', models.CharField(default='task_list', editable=False, max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=1000)),
                ('sno', models.IntegerField(default=0)),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.TaskGroup')),
            ],
        ),
    ]
